CREATE DATABASE ventas;
CREATE TABLE admin(username VARCHAR(30),password VARCHAR(30));
CREATE TABLE ususario(id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, nombre VARCHAR(30), apellido VARCHAR(30), email VARCHAR(50), usado VARCHAR(1));
CREATE TABLE codigo(id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,id_user INT, codigo VARCHAR(7));